### ISSUE TITLE
Add support for Cloudflare DNS

### ISSUE THREAD

**Issue by ricardopolo** [tknarr/opendkim-genkeys#2]

**Comment by tknarr** [comment]
@ricardopolo Do you have access to Cloudflare's DNS service? If so, when I get to this over the weekend can I ask for your assistance in testing it?

**Comment by ricardopolo** [comment]
Yes of course.

You can create a Clouflare account for free https://www.cloudflare.com/ and that includes DNS.
Here is the API, in which you can manage the DNS records  https://api.cloudflare.com/

**Comment by ricardopolo** [comment]
Btw... they provide pythons modules for using their API easier.

**Comment by tknarr** [comment]
Merged, release v1.3

**Comment by tknarr** [comment]
Version 1.3.1 adds a utility to list out zone IDs and domain names for a Cloudflare account.

**Comment by ricardopolo** [comment]
Great! Thanks!
