### ISSUE TITLE
Hosting the DNS

### ISSUE THREAD

**Issue by ricardopolo** [tknarr/opendkim-genkeys#3]
Cloudflare or Route53 has limitation about the number of DNS records.

In our case we have lottts of customers and would like a new DKIM key for each one. So.. have you thought about proving this with a DNS server for own hosting (whitout limits).

Microsoft has something like this for Office 365. They create a new TXT entry (with the DKIM public key) for each customer that sing ups to their services and ask the customer to create in their CNAME to that TXT.

**Comment by tknarr** [comment]
I take it you're discussing the case of a mail service provider hosting the mail servers for a customer's domain, with the DKIM TXT records all hosted in one of your domains? This tool's really intended for the case where the DKIM records are directly in the customer's domain. It will mostly work for your use case, but the `.table` files won't be quite right and I'd have to review the main code to make sure it'll correctly handle the case where the domain the key applies to isn't the domain the TXT record will be looked up in.

I'm not particularly interested in setting up large-scale DNS hosting. There are enough companies out there that can do it better than I can. I'd approach your problem by seeing if I can split things into multiple domains, eg. turning `.provider.net` into `.group1.provider.net`, `.group2.provider.net` and so on, and have a separate zone in Cloudflare/Route53 for each of the new 3LDs with customers spread across the 3LDs.
