### ISSUE TITLE
Add support for custom filename

### ISSUE THREAD

**Issue by strarsis** [tknarr/opendkim-genkeys#9]
It would be great if this tool also offers an option for specifying the output filename prefix/postifx - 
or prepending/appending the passed domain to filename.

**Comment by tknarr** [comment]
How so? As it stands, the key and record text files are named with the format _domainkeyname_._selector_.key (_domainkeyname_ is the second column in the domains.ini file). The domain name vs. domain key name is to allow several related domains to share a single DKIM key. If you're using one key per domain, you can use the domain name as the domain key name. A shortcut like "*" for that might be useful, thinking about it. Were you thinking about a different type of prefixing?

**Comment by strarsis** [comment]
@tknarr: It depends on the key file layout. When all key files are stored in a single folder, e.g. using $domain.selector in filename, it would be great if this tool allows an output filename like this - instead renaming the file after creation which can cause unnecessary trouble. stdout isn't really an option because two files are created, the key file and a txt file with DNS information.

**Comment by tknarr** [comment]
I'm still failing to grok what your proposed filenames would look like. An example showing how they differ from what's currently generated for say the domain "xyzzy.com" with domain key "xyzzy" and selector "201706" would help.
